# Dockerfile to build aria2 Windows binary using ubuntu mingw-w64
# cross compiler chain.
#
# $ sudo docker build -t aria2-mingw - < Dockerfile.mingw
#
# After successful build, windows binary is located at
# /aria2/src/aria2c.exe.  You can copy the binary using following
# commands:
#
# $ sudo docker run --rm -it -v /path/to/dest:/out aria2-mingw cp /aria2/src/aria2c.exe /out

FROM ubuntu:22.04

MAINTAINER Tatsuhiro Tsujikawa

# Change HOST to x86_64-w64-mingw32 to build 64-bit binary
ARG HOST=i686-w64-mingw32

# Define versions for external dependencies
ARG GMP_VERSION=6.3.0
ARG EXPAT_VERSION=2.5.0
ARG SQLITE_YEAR=2023
ARG SQLITE_VERSION=3430100
ARG ZLIB_VERSION=1.3.1
ARG CARES_VERSION=1.19.1
ARG LIBSSH2_VERSION=1.11.0

# It would be better to use nearest ubuntu archive mirror for faster
# downloads.
# RUN sed -ie 's/archive\.ubuntu/jp.archive.ubuntu/g' /etc/apt/sources.list

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y --no-install-recommends \
        make binutils autoconf automake autotools-dev libtool \
        patch ca-certificates \
        pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 \
        autopoint libcppunit-dev libxml2-dev libgcrypt20-dev lzip \
        python3-docutils

RUN curl -L -O https://ftpmirror.gnu.org/gmp/gmp-${GMP_VERSION}.tar.xz && \
    curl -L -O https://github.com/libexpat/libexpat/releases/download/R_${EXPAT_VERSION//./_}/expat-${EXPAT_VERSION}.tar.bz2 && \
    curl -L -O https://www.sqlite.org/${SQLITE_YEAR}/sqlite-autoconf-${SQLITE_VERSION}.tar.gz && \
    curl -L -O https://github.com/madler/zlib/releases/download/v${ZLIB_VERSION}/zlib-${ZLIB_VERSION}.tar.gz && \
    curl -L -O https://github.com/c-ares/c-ares/releases/download/cares-${CARES_VERSION//./_}/c-ares-${CARES_VERSION}.tar.gz && \
    curl -L -O https://libssh2.org/download/libssh2-${LIBSSH2_VERSION}.tar.bz2

RUN tar xf gmp-${GMP_VERSION}.tar.xz && \
    cd gmp-${GMP_VERSION} && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --disable-cxx \
        --enable-fat \
        CFLAGS="-mtune=generic -O2 -g0" && \
    make -j$(nproc) install

RUN tar xf expat-${EXPAT_VERSION}.tar.bz2 && \
    cd expat-${EXPAT_VERSION} && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
    make -j$(nproc) install

RUN tar xf sqlite-autoconf-${SQLITE_VERSION}.tar.gz && \
    cd sqlite-autoconf-${SQLITE_VERSION} && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
    make -j$(nproc) install

RUN tar xf zlib-${ZLIB_VERSION}.tar.gz && \
    cd zlib-${ZLIB_VERSION} && \
    CC=$HOST-gcc \
    AR=$HOST-ar \
    LD=$HOST-ld \
    RANLIB=$HOST-ranlib \
    STRIP=$HOST-strip \
    ./configure \
        --prefix=/usr/local/$HOST \
        --libdir=/usr/local/$HOST/lib \
        --includedir=/usr/local/$HOST/include \
        --static && \
    make -j$(nproc) install

RUN tar xf c-ares-${CARES_VERSION}.tar.gz && \
    cd c-ares-${CARES_VERSION} && \
    ./configure \
        --disable-shared \
        --enable-static \
        --without-random \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
        LIBS="-lws2_32" && \
    make -j$(nproc) install

RUN tar xf libssh2-${LIBSSH2_VERSION}.tar.bz2 && \
    cd libssh2-${LIBSSH2_VERSION} && \
    ./configure \
        --disable-shared \
        --enable-static \
        --prefix=/usr/local/$HOST \
        --host=$HOST \
        --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
        LIBS="-lws2_32" && \
    make -j$(nproc) install

ARG ARIA2_VERSION=master
ARG ARIA2_REF=refs/heads/master

COPY patch /aria2-patch

ADD https://api.github.com/repos/aria2/aria2/git/$ARIA2_REF version.json
RUN git clone -b $ARIA2_VERSION --depth 1 https://github.com/aria2/aria2 && \
    cd aria2 && \
    for patch_file in /aria2-patch/*.patch; do \
        if [ -f "$patch_file" ]; then \
            echo "Applying patch: $patch_file"; \
            git apply "$patch_file"; \
        fi; \
    done && \
    autoreconf -i && ./mingw-config && make -j$(nproc) && \
    $HOST-strip src/aria2c.exe