name: Build aria2

on:
  workflow_dispatch:

env:
  EXPAT_VERSION: "2.6.4"
  SQLITE_VERSION: "3480000"
  CARES_VERSION: "1.34.4"
  LIBSSH2_VERSION: "1.11.1"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            zlib-devel
            sqlite
            git
            unzip
            zip
            tar
            gmp
            gmp-devel
            libssh2
            libssh2-devel
            openssl-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-winpthreads
            autoconf
            automake
            libtool
            pkg-config
            gettext-devel

      - name: Download and extract dependencies
        shell: msys2 {0}
        run: |
          EXPAT_VERSION_UNDERSCORE=$(echo ${{ env.EXPAT_VERSION }} | sed 's/\./_/g')
          EXPAT_VERSION_UNDERSCORE="R_${EXPAT_VERSION_UNDERSCORE}"

          # 下载依赖源码
          curl -L -o expat-${{ env.EXPAT_VERSION }}.tar.gz https://github.com/libexpat/libexpat/releases/download/$EXPAT_VERSION_UNDERSCORE/expat-${{ env.EXPAT_VERSION }}.tar.gz
          curl -L -o sqlite-autoconf-${{ env.SQLITE_VERSION }}.tar.gz https://www.sqlite.org/2025/sqlite-autoconf-${{ env.SQLITE_VERSION }}.tar.gz
          curl -L -o c-ares-${{ env.CARES_VERSION }}.tar.gz https://github.com/c-ares/c-ares/releases/download/v${{ env.CARES_VERSION }}/c-ares-${{ env.CARES_VERSION }}.tar.gz     
          curl -L -o libssh2-${{ env.LIBSSH2_VERSION }}.tar.gz https://www.libssh2.org/download/libssh2-${{ env.LIBSSH2_VERSION }}.tar.gz

          # 验证下载的文件是否有效
          for file in *.tar.gz; do
            if ! tar -tzf "$file" >/dev/null 2>&1; then
              echo "Error: $file is not a valid gzip archive."
              exit 1
            fi
          done

          # 解压源码
          tar -xzf expat-${{ env.EXPAT_VERSION }}.tar.gz
          tar -xzf sqlite-autoconf-${{ env.SQLITE_VERSION }}.tar.gz
          tar -xzf c-ares-${{ env.CARES_VERSION }}.tar.gz
          tar -xzf libssh2-${{ env.LIBSSH2_VERSION }}.tar.gz

      - name: Build expat
        shell: msys2 {0}
        run: |
          cd "expat-${{ env.EXPAT_VERSION }}" || exit 1
          ./configure \
              --disable-shared \
              --enable-static \
              --prefix=/usr/local/x86_64-w64-mingw32 \
              --host=x86_64-w64-mingw32
          make install -j$(nproc)

      - name: Build sqlite
        shell: msys2 {0}
        run: |
          cd "sqlite-autoconf-${{ env.SQLITE_VERSION }}" || exit 1
          ./configure \
              --disable-shared \
              --enable-static \
              --prefix=/usr/local/x86_64-w64-mingw32 \
              --host=x86_64-w64-mingw32
          make install -j$(nproc)

      - name: Build c-ares
        shell: msys2 {0}
        run: |
          cd "c-ares-${{ env.CARES_VERSION }}" || exit 1
          ./configure \
              --disable-shared \
              --enable-static \
              --without-random \
              --disable-tests \
              --prefix=/usr/local/x86_64-w64-mingw32 \
              --host=x86_64-w64-mingw32
          make install -j$(nproc)

      - name: Build libssh2
        shell: msys2 {0}
        run: |
          cd "libssh2-${{ env.LIBSSH2_VERSION }}" || exit 1
          ./configure \
              --disable-shared \
              --enable-static \
              --prefix=/usr/local/x86_64-w64-mingw32 \
              --host=x86_64-w64-mingw32 \
              --with-crypto=wincng \
              LIBS="-lws2_32"
          make install -j$(nproc)

      - name: Build aria2
        shell: msys2 {0}
        run: |
          git clone --depth 1 https://github.com/aria2/aria2
          cd aria2
          if [ -d "$GITHUB_WORKSPACE/patch" ]; then
            for patch_file in $(cygpath -u "$GITHUB_WORKSPACE/patch/*.patch"); do
              patch -p1 < "$patch_file" || exit 1
            done
          fi

          autoreconf -fi || autoreconf -fiv
          ./configure \
              --host=x86_64-w64-mingw32 \
              --prefix=/usr/local/x86_64-w64-mingw32 \
              --without-included-gettext \
              --disable-nls \
              --with-libcares \
              --without-gnutls \
              --without-openssl \
              --with-sqlite3 \
              --without-libxml2 \
              --with-libexpat \
              --with-libz \
              --with-libgmp \
              --with-libssh2 \
              --without-libgcrypt \
              --without-libnettle \
              --with-cppunit-prefix=/usr/local/x86_64-w64-mingw32 \
              ARIA2_STATIC=yes \
              CPPFLAGS="-I/usr/local/x86_64-w64-mingw32/include" \
              LDFLAGS="-L/usr/local/x86_64-w64-mingw32/lib -Wl,--gc-sections,--build-id=none" \
              PKG_CONFIG_PATH="/usr/local/x86_64-w64-mingw32/lib/pkgconfig"
          make -j$(nproc)
          strip -s src/aria2c.exe

      - name: Check ARIA2 version
        shell: cmd
        run: |
          .\aria2\src\aria2c.exe --version
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aria2c.exe
          path: aria2/src/aria2c.exe