name: Release

on:
  workflow_dispatch:

env:
  ARIA2_VERSION: "1.37.0"
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: aria2-${{ env.ARIA2_VERSION }}-*
          merge-multiple: true

      - name: Check if release directory exists
        id: check_release
        run: |
          if [ -d "release" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Merge files
        if: steps.check_release.outputs.exists == 'true'
        run: |
          cd release
          ls