name: Release

on:
  workflow_dispatch:

env:
  ARIA2_VERSION: "1.37.0"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release directory
        run: mkdir -p release

      - name: Get all workflow run IDs
        id: get_run_ids
        run: |
          RUN_IDS=$(gh api repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | .id' \
            --paginate)
          echo "run_ids=$(echo $RUN_IDS | tr '\n' ' ')" >> $GITHUB_OUTPUT  # 使用 $GITHUB_OUTPUT 设置输出变量
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts with specific prefix
        run: |
          for RUN_ID in ${{ steps.get_run_ids.outputs.run_ids }}; do
            echo "Checking artifacts from run $RUN_ID..."
            gh api repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts \
              --jq '.artifacts[] | select(.name | startswith("aria2-${{ env.ARIA2_VERSION }}-")) | .name' \
              --paginate | while read -r ARTIFACT_NAME; do
              echo "Downloading $ARTIFACT_NAME..."
              curl -L -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                -o "release/$ARTIFACT_NAME.zip" \
                "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_NAME/zip"
            done
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check release folder
        id: check_release_folder
        run: |
          echo -e "------------------------------- 文件列表 -------------------------------"
          ls -R release
          if [ -n "$(ls -A release)" ]; then
            echo "Release folder is not empty, proceeding to the next step."
            echo "is_empty=false" >> $GITHUB_OUTPUT
          else
            echo "Release folder is empty, stopping the workflow."
            echo "is_empty=true" >> $GITHUB_OUTPUT
          fi

      - name: Delete existing release if it exists
        if: steps.check_release_folder.outputs.is_empty == 'false'
        run: |
          # 检查是否存在同名 Release
          RELEASE_ID=$(gh api repos/${{ github.repository }}/releases/tags/v${{ env.ARIA2_VERSION }} \
            --jq '.id' \
            --silent || true)
          if [ -n "$RELEASE_ID" ]; then
            echo "Deleting existing release with tag v${{ env.ARIA2_VERSION }}..."
            gh api repos/${{ github.repository }}/releases/$RELEASE_ID \
              --method DELETE
          else
            echo "No existing release found with tag v${{ env.ARIA2_VERSION }}."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog
        run: |
          cat << EOF > CHANGELOG.md
魔改 Aria2 ${{ env.ARIA2_VERSION }} 静态编译版本

## OpenSSL for Linux (64/32-bit)

- Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
- Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
- Libraries: zlib/1.3.1 libxml2/2.9.13 sqlite3/3.48.0 OpenSSL/3.4.0 c-ares/1.34.4 libssh2/1.11.1
- Compiler: gcc 11.4.0
  - built by  x86_64-pc-linux-gnu
  
## Schannel for Windows (64/32-bit)

- Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
- Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
- Libraries: zlib/1.3.1 expat/2.6.4 sqlite3/3.48.0 GMP/6.3.0 c-ares/1.34.4 libssh2/1.11.1
- Compiler: mingw-w64 8.0.0 (alpha) / gcc 10-win32 20220113
  - built by  x86_64-pc-linux-gnu
  - targeting x86_64-w64-mingw32 / i686-w64-mingw32
  
## AppleTLS for macOS (64-bit)

- Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
- Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
- Libraries: zlib/1.2.12 libxml2/2.9.13 sqlite3/3.43.2 AppleTLS c-ares/1.34.4 libssh2/1.11.1
- Compiler: Apple LLVM 15.0.0 (clang-1500.3.9.4)
  - built by  aarch64-apple-darwin23.6.0

EOF
          
      - name: Create GitHub Release and Upload Assets
        if: steps.check_release_folder.outputs.is_empty == 'false'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.ARIA2_VERSION }}  # Release 的标签名称
          name: Aria2 v${{ env.ARIA2_VERSION }} static  # Release 的名称
          body_path: CHANGELOG.md
          draft: false  # 是否作为草稿发布
          prerelease: false  # 是否作为预发布
          files: |
            release/*.zip  # 上传 release 文件夹中的所有 .zip 文件